SELECT * FROM customer

--Q1 What is the tota revenue generated by  male vs female customer?
SELECT gender, SUM(purchase_amount) as revenue
from customer 
group by gender

--Q2 Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) from customer)

--Q3 Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5

--Q4 Compare the average Purchase Amounts between Standard and Express Shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
       COUNT(customer_id) AS Total_customers, 
	   ROUND(AVG(purchase_amount),2) AS average_spend, 
	   ROUND(SUM(purchase_amount),2) as total_revenue				  
FROM customer
WHERE subscription_status IN ('Yes','No')
GROUP BY subscription_status 
ORDER BY average_spend, total_revenue DESC

--Q6 Which 5 products have the highest percentage of purchase wiht discount applied?
SELECT item_purchased,
	   ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

--Q7 Segment customers into New, Returning, and Loyal based on their total number of purchases, and show the count of each segment
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New'
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customer_segment
FROM customer
)


SELECT customer_segment, count(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment

--Q8 What are the \top 3 most purchased products wihtin each category?





